version: "3.0"
services:
  php:
    build: ./.docker/php/7.2
    restart: always
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:ro
    depends_on:
      - php
#  ngrok:
#    image: wernight/ngrok
#    ports:
#      - 4040:4040
#    command: ngrok http nginx:80
  mysql:
    build: ./.docker/mysql
    restart: always
    #ports:
    #- 3306:3306
    volumes:
    - ./runtime/mysql:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
