version: "3.0"
services:
  php:
    build: ./.docker/php/5.6
    restart: always
    volumes:
      - ./src:/var/www/html:cached
    depends_on:
      - mysql
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:ro
    depends_on:
      - php
  ngrok:
    image: wernight/ngrok
    ports:
      - "0.0.0.0:4040:4040"
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      #- NGROK_SUBDOMAIN=<> # only for paid plans
      #- NGROK_REGION=eu
      - NGROK_BINDTLS=true # for enabling HTTPS
      - NGROK_PORT=nginx:80
  mysql:
    build: ./.docker/mysql
    restart: always
    #ports:
    #- 3306:3306
    volumes:
    - ./runtime/mysql:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
